# Generated by Django 2.2 on 2022-02-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
    ]
