# Generated by Django 2.2 on 2022-02-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220214_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'permissions': (('can_published', 'может публиковать'),)},
        ),
    ]
