# Generated by Django 2.2 on 2022-02-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('card_number', models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Номер карты')),
                ('date_of_birth', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
