# Generated by Django 2.2 on 2022-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220214_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verification',
            new_name='is_verified',
        ),
    ]
