# Generated by Django 2.2 on 2022-02-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20220214_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verified', 'может верифицировать'),)},
        ),
    ]
